package com.openai.api.completion;

import lombok.Data;

/**
 * A completion generated by GPT-3
 *
 * https://beta.openai.com/docs/api-reference/completions/create
 */
@Data
public class CompletionChoice {
    String text;
    Integer index;
    LogProbResult logprobs;
    String finish_reason;
}
